### ISSUE TITLE
Add option to donate crypto (bitcoin)

### ISSUE THREAD

**Issue by manreo** [syncthing/website#17]
Hi,
For some people it is easier to donate in Crypto (bitcoin) than using paypal.
I suggest you add donation via this website:
https://www.coinpayments.net/merchant-tools-donations
It support a lot of different crypto (If you do use it, make sure to enable bitcoin and bitcoin-lightning)

Thanks

**Comment by Phoenix616** [comment]
Seems like the old website had an address to donate bitcoin (not sure if that is still active so I wont mention it here or send anything there, we wouldn't want that to get lost would we?). Would love to see that come back and maybe even with some alt coin support?

**Comment by GlenCooper** [comment]
I too would like to see a way to donate via bitcoin.  Re-using the same static donate-to bitcoin address on any site is a terrible for privacy.  I have tested out [opennode.com](https://opennode.com)'s product.  It was very fast and easy to get set up on it.  There are many other similar options out there, but they all involve a decent amount of time & effort to set up.

**Comment by Phoenix616** [comment]
I don't think donations should be processed via yet another proprietary, centralised payment provider. Of course having a static donation address isn't ideal but it's still better than going through a payment provider. If it's really that important to have a unique address per donation then an open source, self-hostable solution like [BTCPay](https://btcpayserver.org/) is the better choice.

**Comment by AudriusButkevicius** [comment]
I think we've concluded on the forum that we will not be adding crypto donation support.

The thread can be found here: https://forum.syncthing.net/t/donate-via-bitcoin/16998/30

Hence closing.

**Comment by Phoenix616** [comment]
Sad to see that you are turning away (potential) donations :S

**Comment by AudriusButkevicius** [comment]
Not really. The reasons are well explained in the forum thread.

**Comment by Phoenix616** [comment]
Don't really see any reasons there against accepting some kind of crypto donation? Only talk there seems to be about non-relevant factors for donations? (Bitcoin fees (non relevant for large amounts) and electricity (not relevant for non-pow coins))

**Comment by AudriusButkevicius** [comment]
There isn't any reason for it either. 

As it was said, if you can buy groceries with a card, you can already donate, if you really want to.

If you can't buy groceries with a card, you are better of spending that money on something else locally.

Everything else just seems to be a coin pushing agenda for the sake of pushing coins, with no real reason behind it.

**Comment by Phoenix616** [comment]
Well the thing is: If you already have a bunch of crypto that you can't buy groceries with then you'll maturely search for other use cases (like donating to open source projects which very often accept a free and open way to transfer value. There isn't really a different way to donate anonymously as sending raw cash isn't supported either)

**Comment by AudriusButkevicius** [comment]
Right, trying to find things to spend bitcoin on, and encouraging others to accept it so you could spend it, to me seems like pushing the agenda.

**Comment by Phoenix616** [comment]
I fail to see how it is "pushing the agenda" when one wants people to adopt some kind of technology that would solve a problem at hand. I don't care which crypto/coin/payment processor is used as long as it checks off certain kind of points: Open, free (as in liberty), secure, forgery-proof, non-centralized and non-government controlled.

**Comment by AudriusButkevicius** [comment]
I don't think there is a problem at hand. I am sure you can already donate if you really want to. 

There is just people "wanting people to adopt" stuff, aka pushing their own agenda.

**Comment by Phoenix616** [comment]
> I don't think there is a problem at hand. I am sure you can already donate if you really want to.

There is: The only way to donate right now is through a centralised payment provider which is not only not available in some countries and requires a bank account/credit card but also tracks and potentially sells data on every single transaction without any form of transparency or accountability.

**Comment by imsodin** [comment]
There's a decision. Many people don't agree with the decision, it may even be a bad decision, it still is our decision - discussion is pointless (and anyway in the wrong place on github).
