### ISSUE TITLE
x86/x64 CPU architecture names on the Syncthing website

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/website#2]
>**Old website:**
>
>![image](https://user-images.githubusercontent.com/5626656/72148264-b544d000-33e3-11ea-8477-bb31cda3dea8.png)
>
>**New website:**
>
>![image](https://user-images.githubusercontent.com/5626656/72148287-be35a180-33e3-11ea-9e0f-525f6d177db9.png)
>
>This is just a suggestion, so please feel free to ignore it if you disagree. Also, a disclaimer - I dislike Intel as a company, so my opinion is biased.
>
>On the old website, the x86/x64 architectures were called "32 bit" and "64 bit" respectively. Now, they are called "Intel 32-bit" and "Intel 64-bit".
>
>1) It it necessary to use the name "Intel" instead of just "32 bit" and "64 bit" as before, or something very clear like "32-bit (x86)" and "64-bit (x64)"?
>
>2) Using the name "Intel" may suggest that the builds are to be used with Intel CPUs only, which is not the case. Also, the actual files are called "386" and "amd64", which can be confusing.
>
>3) For someone knowing a little bit about CPU architectures, "Intel 64-bit" is vague, as it can mean both x64 and IA64. Especially in the Windows context, Microsoft specifically distinguished between "64-bit" meaning IA64, and "x64" meaning AMD64 (see https://en.wikipedia.org/wiki/Windows_XP_editions#Windows_XP_64-Bit_Edition).
>
>Yes, Intel did invent the x86 architecture, but x64 (x86-64 or AMD64) was developed by AMD and calling it "Intel 64-bit" is a little bit unfair, in my opinion. There are also other x86/x64 CPU manufacturers, e.g. VIA. This is why I would like to suggest not to use any vendor names in this case.

Source: https://forum.syncthing.net/t/14319

In the case everyone agrees with my concerns, I would be willing to create a pull request myself, but I first need to know what the actual best names for these architectures would be. Is "32 bit" and "64 bit" (as on the old website) enough, or is something like "32-bit (x86)" and "64-bit (x64)" better?

Another possible issue is that the actual filenames use "386" and "amd64", which do not exactly match the names used on the website.

**Comment by AudriusButkevicius** [comment]
Yeah, we should get rid of the vendor names I think.

**Comment by nekr0z** [comment]
The 32-bit architecture is officially called "IA-32" (Intel Architecture 32), and was indeed developed by Intel. It's a mistake to call it "x86", because it's actually the third generation of x86, and only started being supported since Intel 80386 processor. This, by the way, is why it's a common consensus (and I've seen this in techincal documentation) to call it "x86-32" or "i386".

As for the 64-bit architecture, it was initially called "x86-64" by AMD who developed it, and "EM64T" by Intel when they adopted it. Later Microsoft and Oracle started calling it "x64", AMD started calling it "AMD64", and Intel is now calling it "Intel 64" (since they discontinued their own IA-64 architecture). However, in Open Source community it is a custom to reserve a combination of "intel" and "64" for IA-64 (probably for historical and clarity reasons). So there is basically no universally adopted name for this architecture, unfortunately.

**Comment by nekr0z** [comment]
> Yeah, we should get rid of the vendor names I think.

Unfeasible, I think: there's no way we can throw "ARM" out of the arm* architectures. ;)

**Comment by tomasz1986** [comment]
Yes, I am aware of all the many different names used for the two architectures. I think that it may be useful to focus on the operating systems which Syncthing itself supports.

For example,

1. Windows - Microsoft uses "x86" and "x64".
![image](https://user-images.githubusercontent.com/5626656/72162603-9b1be980-3405-11ea-8f8a-488f963a13bd.png)

2. Linux - There are too many distributions, but just to mention a few, Debian uses "amd64" and "i386",
![image](https://user-images.githubusercontent.com/5626656/72162656-b25ad700-3405-11ea-99e8-5a25948cc275.png)
Ubuntu uses "amd64" and "i386" with additional explanation,
![image](https://user-images.githubusercontent.com/5626656/72162692-c4d51080-3405-11ea-9035-fa0ec5cbb543.png)
Red Hat uses "x86_64",
![image](https://user-images.githubusercontent.com/5626656/72161718-fd73ea80-3403-11ea-8d3f-276079d2878a.png)
while DistroWatch uses "32-bit x86" and "64-bit x86" in their descriptions.
![image](https://user-images.githubusercontent.com/5626656/72162771-eb934700-3405-11ea-9dec-f1490f4c115f.png)

3. Android - The unofficial port is called "Android-x86".

4. macOS - Apple uses "32-bit" and "64-bit" (but x86 is the only architecture they support).

>This, by the way, is why it's a common consensus (and I've seen this in techincal documentation) to call it "x86-32" or "i386".

I am not sure about technical documentation, but from my experience when it comes to common software, it is usually 32/64-bit and x86/x86-64/x64 in the Windows world, and a mixture of the former and i386/amd64 in the Linux world.

Personally, I would go with "32-bit (x86-32)" and "64-bit (x86-64)" for the sake of consistence and understandability.

I have just created a relevant pull request: https://github.com/syncthing/website/pull/3.
