### ISSUE TITLE
Hugo generated content does not match the actual website

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/website#6]
I have been trying to use Hugo to generate the website locally following the instructions from [README.md](https://github.com/syncthing/website/blob/master/README.md), but some of the generated files do not match the actual Syncthing website.

I am not familiar with Hugo itself, but there are lines like

```
{{ with $.Site.Data.release.stable }}
```

e.g. in [release.html](https://github.com/syncthing/website/blob/master/themes/default/layouts/shortcodes/release.html), which suggest than some additional configuration is needed. What kind of adjustments are necessary to generate content that would 100% match the website?

**Comment by calmh** [comment]
See build.sh for the required magic.

**Comment by tomasz1986** [comment]
Thank you very much. I have got it to work. I was trying to build under Windows, and did not even think about checking the .sh file :flushed:.
